name: main
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: tj-actions/puppeteer@v3.2
        with:
          args: yarn install
      - name: Run test
        uses: tj-actions/puppeteer@v3.2
        with:
          args: yarn test
      
 

      - uses: bahmutov/npm-install@v1
      - name: App1 tests
        run: npm install
      - name: Run app2
        run: npm run start
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
