name: main
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
 
 

      - uses: bahmutov/npm-install@v1
      - name: App1 tests
        run: npm install
      - name: Install GitHub Pages Packages
        run: npm install gh-pages --save-dev
      - name: Remove Orgin
        run: git remote rm origin
      - name: Add Orgin
        run: git remote add origin https://github.com/MarketingPip/ImageGenerator.git
    #  - name: Run app2
   #     run: npm run start
      - name: Deploy react app to github pages
        run: npm run deploy
